language: ruby
rvm:
  - 2.3.0
before_install:
  - gem install bundler -v 1.10.3
install:
  - bundle install
cache:
  directories:
    - vendor/bundle
script:
script:
  - cd spec/dummy
  - bundle exec rake db:create RAILS_ENV=test
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:test:prepare
  - cd ../../
  - CI=true bundle exec rspec -cfd
